services:
  mysql:
    image: mysql:8.0
    container_name: locotoons-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: locotoons_dev
    ports:
      - "3308:3306"
    volumes:
      - locotoons_mysql_data:/var/lib/mysql

volumes:
  locotoons_mysql_data:
